name: chat_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  app_minimizer: ^1.0.0+2
  flutter:
    sdk: flutter
  flutter_chat_bubble: ^2.0.2
  flutter_network_connectivity: ^0.0.6
  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.1.0
  google_nav_bar: ^5.0.6
  grouped_list: ^5.1.2
  iconsax: ^0.0.8
  intl: ^0.19.0
  network_info_plus: ^4.1.0
  socket_io_client: ^2.0.3+1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
